### ISSUE TITLE
Remove the dependency of log4j

### ISSUE THREAD

**Issue by locuslin** [neoremind/easy-mapper#1]
It seems that it's more reasonable to include the log API but not log IMPLEMETATION in most toolkits.The user may choose the implementation by himself/herself.
BTW,the feature of auto-registering may make this toolkit more convenient.

**Comment by neoremind** [comment]
By default, org.slf4j:slf4j-api and org.slf4j:slf4j-log4j12 are used as logger. Event spring-core includes implementations of logger, so I think it might not be such a big problem.
You could switch to other slf4j implementation such as logback and exclude log4j like below:

<dependency>
    <groupId>....</groupId>
    <artifactId>....</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
    </exclusions>
</dependency>

As for the auto-register feature, I guess you mean leveraging some kind of Annotation technique to implement that feature. I will consider enhance in the future. 

Thanks for your looking into easy-mapper!
