### ISSUE TITLE
What should I do if I want to copy `Array` and `Interface` ?

### ISSUE THREAD

**Issue by drtrang** [neoremind/easy-mapper#4]
What should I do if I want to copy `Array` and `Interface`( like `List` ) ?
There is a low-level way to solve the second question. Hope you have a better one.

```java
Mapper register = MapperFactory.getCopyByRefMapper().mapClass(UserForm.class, UserView.class)
                .field("persons", "persons", (List list) -> Lists.newArrayList(list))
                .register();
UserView view = register.map(form, UserView.class);
```

**Comment by neoremind** [comment]
Easy-mapper works for the same type of interface or array like List<Integer> or Integer[].  In the example you provided, if persons have the same interface and generic types, it should work, but notice that it copies the reference not deep copying.
